accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'),
    path('', BlogListView.as_view(), name='home'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Post


class BlogListView(ListView):
    model = Post
    template_name = 'blog/home.html'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class BlogCreateView(CreateView):
    model = Post
    template_name = 'blog/post_new.html'
    fields = ['title', 'author', 'body']


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    fields = ['title', 'body']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('home')

blog/templates/base.html
{% load static %}
<html lang='en'>

<head>
    <title>Django blog</title>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400'
          rel='stylesheet'>
    <link href='{% static 'css/base.css' %}' rel='stylesheet'>
</head>

<body>
    <header>
        <div class='nav-left'>
            <h1><a href='{% url 'home' %}'>Django blog</a></h1>
        </div>
        <div class='nav-right'>
            <a href='{% url 'post_new' %}'>+ New Blog Post</a>
        </div>
    </header>
    <div>
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% for post in post_list %}
            <div class='post-entry'>
                <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
                <p>{{ post.body }}</p>
            </div>
        {% endfor %}
{% else %}
    <p>You are not logged in</p>
{% endif %}
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete post</h1>
<form action='' method='post'>{% csrf_token %}
    <p>Are you sure you want to delete '{{ post.title }}'?</p>
    <input type='submit' value='Confirm'>
</form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class='post-entry'>
    <h2>{{ object.title }}</h2>
    <p>{{ object.body }}</p>
</div>
<div>
    <p><a href='{% url 'post_edit' post.pk %}'>+ Edit Blog Post</a></p>
    <p><a href='{% url 'post_delete' post.pk %}'>+ Delete Blog Post</a></p>
</div>
{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit post</h1>
<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Update'>
</form>
{% endblock content %}

blog/templates/blog/post_new.html
{% extends 'base.html' %}

{% block content %}
<h1>New post</h1>
<form action='' method='post'>{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save'>
</form>
{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% for post in post_list %}
            <div class='post-entry'>
                <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
                <p>{{ post.body }}</p>
            </div>
{% endfor %}
{% else %}
  <p>You are not logged in</p>
  <a href='{% url 'login' %}'>Log In</a>
{% endif %}
{% endblock content %}

templates/base.html
{% load static %}
<html lang='en'>

<head>
    <title>Django blog</title>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400'
          rel='stylesheet'>
    <link href='{% static 'css/base.css' %}' rel='stylesheet'>
</head>

<body>
    <header>
        <div class='nav-left'>
            <h1><a href='{% url 'home' %}'>Django blog</a></h1>
        </div>
        <div class='nav-right'>
            {% if user.is_authenticated %}
                <p>Hi {{ user.username }}!&emsp;</p>
                <p><a href='{% url 'post_new' %}'>+ New Blog Post</a>&emsp;</p>
                <p><a href="{% url 'logout' %}">Log out</a>&emsp;</p>
            {% else %}
                <p><a href='{% url 'login' %}'>Log In</a>&emsp;</p>
                <p><a href="{% url 'signup' %}">Sign Up</a>&emsp;</p>
            {% endif %}
        </div>
    </header>
    <div>
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>